name: flutter_advanced_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10+1
  retrofit: ^4.1.0
  analyzer: ^6.4.1
  dio: ^5.5.0+1
  retrofit_generator: ^8.1.2
  json_annotation: ^4.9.0
  dartz: ^0.10.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.1
  freezed: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.jpg
    - assets/images/onboarding_logo2.jpg
    - assets/images/onboarding_logo3.jpg
    - assets/images/onboarding_logo3.jpg
    - assets/images/right_arrow_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/hollow_circle_ic.svg
    - assets/images/login.png

  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600


